### PR TITLE
CAN communiator mkII

### PR DESCRIPTION
**Pull request by cmastudios**
Here is the updated breadboard and schematic using an ATmega. I designed this to be able to take up to 4 analog inputs but that can be modified. It also has a 3-pin header for reprogramming.

Shopping list: http://www.digikey.com/short/qtqn1m 

out2
output

### CODE REVIEW

**Comment by tommkelly** [comment]
Okay, first thing: this looks _awesome_. It's way cleaner than the older one (I'm liking the lack of via's), and I love the idea with the 3-pin header. I was working under the assumption that we would put the Mega in a chip holder- the jury's still out on that one, soldering the chips straight in makes me a little nervous, but still: great idea. A few notes, though:

- I see a lot of surface mount components, and I honestly don't know if we're capable of soldering those. I'd feel better if they were swapped out for plain old through-hole.
- I know I haven't mentioned it in a while, but I do still like the idea of using molex connectors in place of screw terminals. My ideal setup is 2-pin connectors for power/ground and CANH/CANL, then a single connector with as many pins as we have inputs, maybe separated by analog/digital.
- There's a tradeoff with real estate on the board here, but if we're going to be using the ATMega, we might as well have access to as many pins as possible. We definitely want all of the analog pins, and at least pin 3 (for the external interrupt) as far as the digital pins go.
- I know we didn't get it working on the breadboard this Saturday, but we've got that oscillator and the pullup resistor on the reset pin all set up and ready to go. I wonder if it's worth it to get the Mega on the external clock.

Still though: looks great. If you get a chance to look into those changes before next Saturday, awesome, if not, don't sweat it. I'll look into it myself as well.

**Comment by MichaelRyanGreer** [comment]
I know a professor that has a smt component soldering workstation; we might be able to borrow it. Additionally, we can buy our own for ~$80, it might be a good investment as that would mean smaller and cheaper pcbs and components. Let me know if y'all are interested.

Additionally, we should put the racing logo on the silkscreen: http://sae.wustl.edu/logo.png

Edit: Also, if you could round the corners on the board that would be great. It makes them a lot more pleasant to work with. It would be helpful for the board to have some mounting holes on it to secure to wherever we end up putting them. Overall though, these things look awesome and they take up way less space than an Arduino doing the same thing. Great job.

**Comment by MichaelRyanGreer** [comment]
Also, if you could round the corners on the board that would be great. It makes them a lot more pleasant to work with.

**Comment by cmastudios** [comment]
Here's what the board looks like after making most of these changes.

pcb

The screw terminals have been replaced with [this connector](https://www.digikey.com/product-detail/en/molex-llc/22-23-2021/WM4200-ND/26667) but it could be swapped out for something else.

The inputs on the left are in pairs and connect to:

1. VCC/GND
2. Pin 3 (int) / Pin 4 (PWM)
3. Analog 4/5
4. Analog 2/3
5. Analog 0/1
6. CANH/L

**Comment by MichaelRyanGreer** [comment]
Ok, that looks awesome. Great job, I think we're really close to finalizing design. Just a few notes:

1. Do you have the part number for the corresponding female connector to the part you linked?

2. We might want to consider using right-angle headers instead of vertical headers for the connectors; that will improve cabling management by keeping everything nice and flat. Luckily, if we use [these](https://www.digikey.com/product-detail/en/molex-llc/22-05-3021/WM4300-ND/26689), we won't have to modify the board design at all, seeing as it should have the same footprint.

**Comment by MichaelRyanGreer** [comment]
Also, if you want to put some kind of "Designed by Connor Monahan" and whoever else helped, feel free. There's a lot of real estate on the reverse side, so it shouldn't be any kind of problem.

**Comment by cmastudios** [comment]
Yeah the right angle headers should work because the spacing is 0.1". [These](https://www.digikey.com/product-detail/en/molex-llc/22-01-2027/WM2011-ND/171991) should be the correct female connectors.

**Comment by cmastudios** [comment]
Here's the PCB with 2M clearance holes and more space to accomodate them: 
pcb

**Pull request merged**
